### ISSUE TITLE
Support for Minetest versions below 5.6.0

### ISSUE THREAD

**Issue by ApolloX939** [grorp/ggraffiti#1]
Directly from logs:

```
2022-11-07 16:38:56: ERROR[Main]: ServerError: AsyncErr: Lua: Runtime error from mod 'ggraffiti' in callback item_OnUse(): /minetest/bin/../mods/ggraffiti/init.lua:134: attempt to call method 'add_wear_by_uses' (a nil value)
2022-11-07 16:38:56: ERROR[Main]: stack traceback:
2022-11-07 16:38:56: ERROR[Main]: 	/minetest/bin/../mods/ggraffiti/init.lua:134: in function </minetest/bin/../mods/ggraffiti/init.lua:133>
2022-11-07 16:38:56: ERROR[Main]: 	(tail call): ?
```

Minetest: 5.5.0
GGraffiti: v1.0.0-alpha.4 (I.E. Latest on Master)

I'm thinking your using something in a newer version of Minetest, either make it adapt between versions that don't support it or at least make the minimum version known (by either manually downloading each version till you get one that works, or at least making a check for that function existence and abort if it doesn't exist with an error message that's more clearer).

**Comment by ApolloX939** [comment]
Looks like that feature was added in Minetest 5.6.0

**Comment by ApolloX939** [comment]
Minetest 5.6.0 Source:

- [https://github.com/minetest/minetest/blob/5.6.0/src/script/lua_api/l_item.cpp#L360-L377](https://github.com/minetest/minetest/blob/5.6.0/src/script/lua_api/l_item.cpp#L360-L377)
- [https://github.com/minetest/minetest/blob/5.6.0/src/script/lua_api/l_item.h#L116-L123](https://github.com/minetest/minetest/blob/5.6.0/src/script/lua_api/l_item.h#L116-L123)

**Comment by ApolloX939** [comment]
I'd be almost insane to try implementing my own, just need their `calculateResultWear()` and I should be able to make a PR with a fix so if it doesn't exist then we just use our own.

> Looks like the sources don't clearly show where `calculateResultWear()` is defined, so I'll be developing my own, since the math is fairly straight forward: `max uses / 65536`.

Ok so even with me writing my own I'd have to include updating the vector stuff, and run into anything else that's different in 5.5.0 to 5.6.0... which appears to be more than I thought.

Looks like your better off just putting up a notice for Minetest 5.6.0 minimum, and you can now fill in that on contentdb so folks like me don't try running it without knowing about it first.

**Comment by ApolloX939** [comment]
I'm going to go ahead and update my minetest... now that I know there's cool stuff out there I'd be interested in.

**Comment by ApolloX939** [comment]
Oh, yeah might want to leave this open so you can make note to update contentDB and the main README to include mentioning minimum Minetest version 5.6.0

**Comment by grorp** [comment]
Hi, thank you for the feedback (and the stuff beyond feedback) :-) I've now set the minimum supported Minetest version on ContentDB to 5.6.0 and put a note into the README. Maybe at some point I'll also try to make the mod compatible with older versions myself. I'll leave the issue open for now.

**Comment by ApolloX939** [comment]
Yeah I was thinking of trying to make it cross compatible but you'll find needing to port over vector and add_wear_by_uses changes. (possibly more changes too)

**Comment by grorp** [comment]
Minimum version is now 5.9.0, closing this issue.
