### ISSUE TITLE
[Feature]: Anti Ggraffiti Node or Area

### ISSUE THREAD

**Issue by ApolloX939** [grorp/ggraffiti#2]
I can see it where someone will go to someone else's home while they are offline or away and graffiti their home, which can get annoying once you have that happen to them on multiple occasions.

So what if we had either a node which can't be graffiti-ed or even something that blocks the use of graffiti cans (except maybe the anti-graffiti)?

I'm leaning towards an area that way someone doesn't need to make a house out of the blocks just to get a anti graffiti house.

**Comment by ApolloX939** [comment]
I'm thinking a simple way to limit where players can paint is if the node it protected and if they have access, so players can protect their home(s) and not have them graffiti-ed.

**Comment by grorp** [comment]
The graffiti already respects `minetest.is_protected`:

https://github.com/grorp/ggraffiti/blob/e62596325f14d8a013e69f57ae2c65cefe4dc8d3/init.lua#L58-L61

That means it already supports protection mods such as "Areas" or "Protector Redo". Do you think that is enough?

**Comment by ApolloX939** [comment]
Ah, ok, nope that should take care of that.

> Guess I should have looked at the code first before making the issue.
