### ISSUE TITLE
add screenshots to contentDB

### ISSUE THREAD

**Issue by Lemente** [grorp/ggraffiti#7]
From the only screenshot currently visible, I didn't really understand that you could actually paint pixel by pixel.

Here are two experiments done with ggraffiti, in case you would want to use those. No credit necessary, consider CC0.
![minetest_Guu7PNwCpD](https://user-images.githubusercontent.com/27686967/221692418-a1758575-ff64-472d-9c32-d65b42f50fe2.png)
![screenshot_20230119_184401](https://user-images.githubusercontent.com/27686967/221692889-0bcb1446-424b-4858-81a8-9da3168939a8.png)

**Comment by grorp** [comment]
Thank you very much, these are great! I'll add them.

**Comment by grorp** [comment]
Done.
