### ISSUE TITLE
Cave Painting Concept

### ISSUE THREAD

**Issue by Lemente** [grorp/ggraffiti#9]
At the end of the month me and a few colleagues will be visiting the Lascaux cave in France with the teachers from the Minestory project and their students.
The next day will be dedicated to opresenting their Minetest projects, as well as participating to a series of small activities. We are thinking about proposing them a cave painting activity in Minetest using your mod.

I was wondering about adapting this mod as a cave painting mod, with pigments and tools coherent with the time period (charcoal, ochre, etc).

I don't know if I will have any time to dedicate to that, but I wanted to put the idea out there!
I am wondering if it should be another mod that depends on ggraffiti.
Would that be feasible in your opinion? What would be the easiest way to create new items for painting?

Thanks for the great mod!

**Comment by grorp** [comment]
Hey,
that sounds like a great use case for this mod :)

It should definitely be possible to adapt this mod for cave paintings. However, it currently doesn't provide an API for registering new "brush" items, so you'd either have to modify the mod or do it "the hacky way".  It probably makes sense to add an API, but doing that right would take some time.

With the current version of the mod, it is possible to do something like this ("the hacky way"):

```lua
-- put this into a mod that depends on "default" and "ggraffiti"
-- included examples:
--   * default:coal_lump    -> basic (constant color, size = 1)
--   * default:coalblock    -> custom size (size = 3)
--   * default:apple        -> remover
--   * default:diamondblock -> dynamic color (rainbow-like)

local ggraffiti_range = minetest.registered_items["ggraffiti:spray_can_red"].range
local ggraffiti_on_use = minetest.registered_items["ggraffiti:spray_can_red"].on_use

-- basic (constant color, size = 1)
minetest.override_item("default:coal_lump", {
    range = ggraffiti_range,
    on_use = ggraffiti_on_use,
    _ggraffiti_spray_can = {
        color = "#111100",
    },
})

-- custom size (size = 3)
minetest.override_item("default:coalblock", {
    range = ggraffiti_range,
    on_use = function(item, player, pointed_thing)
        local meta = item:get_meta()
        meta:set_int("ggraffiti_size", 3)
        return ggraffiti_on_use(item, player, pointed_thing)
    end,
    _ggraffiti_spray_can = {
        color = "#111100",
    },
})

-- remover
minetest.override_item("default:apple", {
    range = ggraffiti_range,
    on_use = ggraffiti_on_use,
    _ggraffiti_spray_can = {
        remover = true,
    },
})

-- https://stackoverflow.com/a/68323185
local function hslToRgb(h, s, l)
    h = h / 360
    s = s / 100
    l = l / 100

    local r, g, b

    if s == 0 then
        r, g, b = l, l, l -- achromatic
    else
        local function hue2rgb(p, q, t)
            if t < 0 then t = t + 1 end
            if t > 1 then t = t - 1 end
            if t < 1 / 6 then return p + (q - p) * 6 * t end
            if t < 1 / 2 then return q end
            if t < 2 / 3 then return p + (q - p) * (2 / 3 - t) * 6 end
            return p
        end

        local q = l < 0.5 and l * (1 + s) or l + s - l * s
        local p = 2 * l - q
        r = hue2rgb(p, q, h + 1 / 3)
        g = hue2rgb(p, q, h)
        b = hue2rgb(p, q, h - 1 / 3)
    end

    return r * 255, g * 255, b * 255
end

local function update_color(item)
    local t = math.floor(minetest.get_us_time() / 10000)
    local h, s, l = t % 360, t % 100, 50 + (t + 388) % 50
    local r, g, b = hslToRgb(h, s, l)
    local rgb = { r = r, g = g, b = b}

    local meta = item:get_meta()
    meta:set_string("ggraffiti_rgb_color", minetest.serialize(rgb))
end

-- dynamic color (rainbow-like)
minetest.override_item("default:diamondblock", {
    range = ggraffiti_range,
    on_use = function(item, player, pointed_thing)
        update_color(item)
        return ggraffiti_on_use(item, player, pointed_thing)
    end,
    _ggraffiti_spray_can = {
        rgb = true,
    },
})

minetest.register_globalstep(function()
    for _, player in ipairs(minetest.get_connected_players()) do
        local item = player:get_wielded_item()
        local control = player:get_player_control()
        if item:get_name() == "default:diamondblock" and control.dig then
            update_color(item)
            player:set_wielded_item(item)
        end
    end
end)
```

(Actually, this isn't as bad/"hacky" as I thought.)

**Comment by Lemente** [comment]
I will experiment with that, thanks a lot!

**Comment by Lemente** [comment]
I uploaded an early WIP here https://github.com/Lemente/cave_painting
I need to properly credit you, thanks again!
Can I assume the code above is under AGPL 3.0, like the rest of ggraffiti?

(you'll need the rpg16 texture pack to see all the textures, I used random minerals as placeholders)

I added a feature where you can change the brush size by right clicking.

**Comment by grorp** [comment]
That looks great! You can consider my example code CC0.  
I've seen on Discord that your event has already started. I hope it goes well / went well :)
